on:
  push:
    tags:
      - "v*"

name: Release extension

jobs:
  build:
    name: Release extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Use Node.js
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm install
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Verify Java version
        run: java -version
      - name: Build venus
        run: npx grunt buildvenus
      - name: Build extension
        run: npm run compile
      - name: Package extension
        run: npm run package
      - name: prepare version string
        id: prep_version
        run: |
          export test_version=$(echo ${{ github.ref_name }} |  sed 's/v//g')
          export is_prerelease=$(if [[ $test_version == *"-"* ]]; then echo "true"; else echo "false"; fi)
          echo "version=$test_version" >> "$GITHUB_ENV"
          echo "is_prerelease=$is_prerelease" >> "$GITHUB_ENV"
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ env.version }}
          draft: false
          prerelease: ${{ env.is_prerelease }}
          files: ./**.vsix
      - name: Vscode release plugin
        if: ${{ !contains(github.ref_name, '-') }}
        env:
          PUBLISHER_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
        run: |
          npm run publish -- -p ${{ secrets.PUBLISHER_TOKEN }}
      # - name: Publish to Open VSX Registry
      #   if: ${{ !contains(github.ref_name, '-') }}
      #   uses: HaaLeo/publish-vscode-extension@v1
      #   with:
      #     pat: ${{ secrets.OPEN_VSX_TOKEN }